<?php
namespace K48\SEM2;

class HocVien
{
    public $name;

    function setName(string $name) {
        if ($name)
            $this->name = $name;
        return $this;
    }

    function getName() {
        return $this->name;
    }
}

// region Use Object
/*$hocvien = new HocVien();
$hocvien->setName('Duy');
echo $hocvien->getName(), PHP_EOL;*/

//echo (new HocVien())->setName('Dang Tuan')->getName();
// endregion

class HocVienMoi extends HocVien
{
    protected $gender;

    function setGender(string $gender) {
        $this->gender = $gender;
    }

    function getGender() {
        return $this->gender;
    }

    function getName() {
        return 'Hoc Vien Moi';
    }
}

/*$newHV = new HocVienMoi();
$newHV->setName('Duy');
$newHV->setGender('nam');
echo 'Ten: ', $newHV->getName(), ' - Gioi tinh: ', $newHV->getGender();*/

class HocVienTre extends HocVien
{
    protected $age;

    function setAge(string $age) {
        $this->age = $age;
    }

    function getAge() {
        return $this->age;
    }
}

class HocVienChau extends HocVienMoi
{
//    protected $gender;
    protected $email;

    function __construct()
    {
        $this->email = 'chau111@mail.com';
    }

    /*function __destruct()
    {
        echo "Delete demo email {$this->email}", PHP_EOL;
    }*/

    function setGender(string $gender) {
        $this->gender = 1;
    }

    function getGender() {
        return $this->gender;
    }

    function getEmail() {
        return $this->email;
    }

    public function getName()
    {
//        return parent::getName(); // TODO: Change the autogenerated stub
        return 'Hoc Vien Chau PHP';
    }

    public function showName() {
//        return $this->getName();
        self::getName();
        return HocVien::getName() .' - '. HocVienMoi::getName();
    }
}

$hvChau = new HocVienChau();
//echo $hvChau->getEmail(), PHP_EOL;
$hvChau->setName('Tuan K48');
//echo $hvChau->getName(), PHP_EOL;
echo $hvChau->showName(), PHP_EOL;
